backend:
  name: git-gateway
  branch: main

# when using the default proxy server port
local_backend: true

# Internationalisation
locale: 'fr'
#i18n:
#  structure: multiple_folders
#  locales: [en, fr]
#  default_locale: fr

media_folder: static/img
public_folder: /img

collections:

  # Our posts
  - name: 'posts'
    label: 'Actualités'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    path: "{{year}}/{{month}}/{{slug}}"
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - { label: 'Extrait', name: 'description', widget: 'text', required: false }
      - { label: 'Contenu', name: 'body', widget: 'markdown', required: false  }

  # Configuration
  - label: "Configuration"
    name: "setup"
    files:

      # Menus
      - label: "Menus"
        name: "menu"
        format: 'yml'
        folder: 'data/menus'
        create: true
        fields:
          - label: Liens
            name: item
            widget: list
            fields:
              - { label: Titre, name: title, widget: string }
              - { label: Lien, name: link, widget: string }