backend:
  name: git-gateway
  branch: main

# Localhost
local_backend: true

# Internationalisation
locale: 'fr'
# i18n:
#  structure: multiple_folders
#  locales: [fr, en]
#  default_locale: fr

# Media
media_folder: assets/images/uploads
public_folder: /images/uploads

# Slug
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

# Fields
index_field: &INDEX_FIELD
  name: index
  label: Index
  widget: hidden
  default: false
  required: false
  i18n: duplicate

draft_field: &DRAFT_FIELD
  name: draft
  label: Brouillon
  widget: boolean
  default: true
  required: false
  i18n: duplicate

image_field: &IMAGE_FIELD
  name: image
  label: Image
  widget: image 
  required: false 
  i18n: duplicate 
  media_library: 
    config: 
      max_file_size: 512000
  hint: '500Ko max, Compress image before send it: https://tinypng.com/'
  media_folder: "/assets/images/uploads"
  public_folder: "/images/uploads"

title_field: &TITLE_FIELD
  name: title
  label: Titre
  widget: string
  i18n: true

description_field: &DESCRIPTION_FIELD
  name: description
  label: Description
  widget: text
  required: false
  i18n: true

content_field: &CONTENT_FIELD
  name: body
  label: Contenu
  widget: markdown
  required: false
  i18n: true

hero_fields: &HERO_FIELDS
  name: hero
  label: Hero
  widget: object
  required: false
  i18n: true 
  collapsed: true
  fields:
    - *TITLE_FIELD
    - { name: text, label: Texte, widget: string, required: false, i18n: true }
    - name: cta
      label: CTA
      widget: object
      required: false
      i18n: true 
      fields:
        - { name: text, label: Texte, widget: string, i18n: true }
        - { name: url, label: URL, widget: string, i18n: true }
    - *IMAGE_FIELD

seo_fields: &SEO_FIELDS
  name: seo
  label: SEO
  widget: object
  required: false
  i18n: true 
  collapsed: true
  fields:
    - { name: title, label: Titre, widget: string, required: false, i18n: true }
    - *DESCRIPTION_FIELD
    - *IMAGE_FIELD

featured_image_fields: &FEATURED_IMAGE_FIELDS
  name: featured_image
  label: Featured image
  widget: object
  fields:
    - *IMAGE_FIELD
    - { name: alt, label: Alternative text, widget: string, required: false, i18n: true }
    - { name: credits, label: Credits, widget: string, required: false, i18n: true }
    - { name: legend, label: Legend, widget: string, required: false, i18n: true }

categories_field: &CATEGORIES_FIELD
  name: categories
  label: Categories
  widget: relation
  collection: categories
  search_fields: ["title"]
  value_field: "{{slug}}"
  display_fields: ["title"]
  required: false

authors_field: &AUTHORS_FIELD
  name: authors
  label: Authors
  widget: relation
  collection: authors
  search_fields: ["title"]
  value_field: "{{slug}}"
  display_fields: ["title"]
  required: false

links_fields: &LINKS_FIELDS
  name: item
  label: Links
  widget: list
  i18n: true
  required: false
  fields:
    - *TITLE_FIELD
    - { label: Lien, name: link, widget: string, i18n: true }
    - { label: "Blank?", name: "blank", widget: "boolean", default: false, required: false, i18n: duplicate }



# Collections
collections:

  # Posts
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: 'content/posts'
    editor:
      preview: false
    create: true
    #i18n: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    path: "{{year}}/{{month}}/{{slug}}"
    filter: { field: index, value: false }
    fields:
      - *INDEX_FIELD # Hack to ignore _index
      - *DRAFT_FIELD
      - *TITLE_FIELD
      - { label: 'Date de publication', name: 'date', widget: 'datetime', i18n: duplicate }
      - *CATEGORIES_FIELD
      - *AUTHORS_FIELD
      - *IMAGE_FIELD
      - *DESCRIPTION_FIELD
      - *CONTENT_FIELD


  # Categories (taxonomy)
  - name: 'categories'
    label: 'Categories'
    label_singular: 'Category'
    folder: 'content/categories'
    editor:
      preview: false
    create: true
    #i18n: true
    nested:
      depth: 2
    path: '{{slug}}/_index'
    slug: '{{slug}}'
    filter: { field: index, value: false }
    fields:
      - *TITLE_FIELD
  

  # Authors (taxonomy)
  - name: 'authors'
    label: 'Authors'
    label_singular: 'Author'
    folder: 'content/authors'
    editor:
      preview: false
    create: true
    #i18n: true
    filter: { field: index, value: false }
    nested:
      depth: 2
    path: '{{slug}}/_index'
    slug: '{{slug}}'
    fields:
      - *INDEX_FIELD # Hack to ignore _index
      - <<: *TITLE_FIELD
        label: Nom
      - *DESCRIPTION_FIELD
      - { label: Email, name: email, widget: string, required: false, i18n: duplicate }
      - { label: Twitter, name: twitter, widget: string, required: false, i18n: duplicate, hint: "Username" }
      - { label: Site web, name: website, widget: string, required: false, i18n: duplicate }

  # Index pages
  - name: 'index'
    label: 'Index pages'
    folder: 'content'
    editor:
      preview: false
    create: false
    #i18n: true
    filter: { field: index, value: true }
    nested:
      depth: 3
    fields:
      - { label: "Index", name: "index", widget: "hidden", default: true, required: false, i18n: duplicate } # Hack to ignore _index
      - *TITLE_FIELD
      - *HERO_FIELDS
      - *SEO_FIELDS
  
  # Pages
  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    folder: 'content/pages'
    editor:
      preview: false
    create: true
    #i18n: true
    nested:
      depth: 3
    slug: '{{slug}}'
    fields:
      - *INDEX_FIELD # Hack to ignore _index
      - { label: "Brouillon", name: "draft", widget: "boolean", default: true, required: false, i18n: duplicate }
      - *TITLE_FIELD
      - *IMAGE_FIELD
      - *DESCRIPTION_FIELD
      - *CONTENT_FIELD
    meta: { path: { widget: string, label: 'Chemin', index_file: 'index', hint: 'Arborescence complete : séparer les niveaux par un /' } }

  # Menus
  - name: menu
    label: Menus
    editor:
      preview: false
    # i18n: 
    #   structure: single_file
    #   locales: [fr, en]
    files:

      - name: primary
        label: Principal
        file: 'data/menu/primary.yml'
        i18n: true
        fields:
          - *LINKS_FIELDS
      - name: "secondary"
        label: "Secondaire"
        file: 'data/menu/secondary.yml'
        i18n: true
        fields:
          - *LINKS_FIELDS
      - name: "legal"
        label: "Légal"
        file: 'data/menu/legal.yml'
        i18n: true
        fields:
          - *LINKS_FIELDS
      - name: "social"
        label: "Réseaux sociaux"
        file: 'data/menu/social.yml'
        i18n: true
        fields:
          - *LINKS_FIELDS

  # Config
  - name: config
    label: Config
    editor:
      preview: false
    # i18n: 
    #   structure: single_file
    #   locales: [fr, en]
    files:

      - name: seo
        label: SEO
        file: 'data/seo.yml'
        i18n: true
        fields:
          - { label: Nom du site, name: title, widget: string, i18n: true }
          - *DESCRIPTION_FIELD
          - *IMAGE_FIELD
